bldr:
    name: alexkovalevych/jira-api
    description: Jira API library
    profiles:
        travis:
            description: Travis Profile
            jobs:
                - prepare
                - lint
                - test
        local:
            description: Local Development Profile
            jobs:
                - testLocal
                - watch
    jobs:
        prepare:
            tasks:
                -
                    type: exec
                    failOnError: true
                    executable: composer
                    arguments: [-q, install, --prefer-dist]
                -
                    type: notify
                    message: Prepare Task Finished
        lint:
            description: Lints the files of the project
            tasks:
                -
                    type: apply
                    failOnError: true
                    src:
                        -
                            path: [src, tests]
                            files: "*.php"
                            recursive: true
                    output: /dev/null
                    executable: php
                    arguments: [-l]

        test:
            description: Runs the PHPUnit Tests
            tasks:
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments:
                        - vendor/bin/phpunit
                        - --coverage-html=build/coverage
                        - --coverage-text=php://stdout
        testLocal:
            description: Runs the PHPUnit Tests
            tasks:
                -
                    type: exec
                    executable: clear
                -
                    type: exec
                    executable: php
                    arguments:
                        - vendor/bin/phpunit
                        #- --group=now
        watch:
            description: Watch Task for Local Development
            tasks:
                -
                    type: watch
                    src:
                        -
                            path: ["src", "tests"]
                            files: "*.php"
                            recursive: true
                    task: testLocal
